# Generated by Django 6.0.1 on 2026-02-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_phone_alter_user_email_profile'),
        ('users', '0004_user_created_at'),
    ]

    operations = [
    ]
