# Generated by Django 6.0.1 on 2026-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('tournaments', 'Турниры'), ('teams', 'Команды'), ('updates', 'Обновления'), ('patches', 'Патчи')], default='teams', max_length=50, verbose_name='Тип новости'),
            preserve_default=False,
        ),
    ]
