# Generated by Django 6.0.1 on 2026-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_img_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Изображение'),
        ),
    ]
