# Generated by Django 6.0.1 on 2026-02-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_img'),
        ('news', '0003_mainnews_alter_news_img'),
    ]

    operations = [
    ]
