# Generated by Django 6.0.1 on 2026-01-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
                ('prize_pool', models.CharField(max_length=50)),
                ('completion_date', models.DateField()),
                ('teams_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название турнира')),
                ('game', models.CharField(max_length=255, verbose_name='Игра')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('prize_pool', models.CharField(max_length=50, verbose_name='Призовой фонд')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('max_teams', models.PositiveIntegerField(default=16, verbose_name='Максимальное количество команд')),
                ('registred_teams', models.PositiveIntegerField(default=0, verbose_name='Зарегистрированные команды')),
                ('format', models.CharField(choices=[('single_elim', 'Single Elimination'), ('double_elim', 'Double Elimination'), ('swiss', 'Swiss System'), ('round_robin', 'Round Robin')], default='single_elim', max_length=20, verbose_name='Формат турнира')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('status', models.CharField(choices=[('registration', 'Открыта регистрация'), ('upcoming', 'Скоро'), ('completed', 'Завершён')], default='registration', max_length=20, verbose_name='Статус турнира')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
