# Generated by Django 6.0.1 on 2026-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasttournament',
            options={'ordering': ['-completion_date'], 'verbose_name': 'Прошлый турнир', 'verbose_name_plural': 'Прошлые турниры'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-start_date'], 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('standoff2', 'Standoff 2'), ('pubg', 'PUBG Mobile'), ('csgo', 'CS:GO'), ('dota2', 'Dota 2'), ('valorant', 'Valorant'), ('freefire', 'Free Fire'), ('brawlstars', 'Brawl Stars'), ('apex', 'Apex Legends')], max_length=50, verbose_name='Игра'),
        ),
    ]
